#!/bin/bash
# AUTHOR: DEBJIT RAY
# DATE: 09/12/2013
# DESCRIPTION: RUNS ALL THE QUALITY CONTROL AND PREPROCESSING STEPS
# PLATFORM: HPC [COPY THIS FILE ON THE HPC AND RUN ON THE HPC HOME] AS $ sh 0B.QAPreprocessing.sh
# NOTES: [FILE1]=SRR527218 AND [FILE2]=SRR527219, RAW SEQUENCE FILES

# EXPORT THE BIN2 PATH
export PATH=$HOME/bin2:$PATH

## QUALITY CONTROL ANALYSIS ON THE 2 SEQUENCES
echo `bin/FastQC/./fastqc Sequencing/SRR527218.fastq`
echo `bin/FastQC/./fastqc Sequencing/SRR527219.fastq`

## DOWNLOAD THE REPORTS WITH FUGU TO YOUR LOCAL MACHINE AND ANALYZE [CANNOT USE COMMAND LINE ON HPC]

## BASED ON THE ABOVE TEST ADAPTER TRIMMING
echo `fastx_clipper -v -i SRR527218.fastq -Q 33 -a GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG -o SRR527218_trimmed.fastq`
echo `fastx_clipper -v -i SRR527219.fastq -Q 33 -a GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG -o SRR527219_trimmed.fastq`
